baseurl = ""
languageCode = "en-us"
title = "Curso-R"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
relativeurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Digitalcraftsman"
	description = "A material design theme for documentations."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/curso-r/verao2017"

	version = ""
	logo = "logo-curso-r.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "curso-r"
	email   = "dfalbel@gmail.com"


[[menu.main]]
	name   = "Curso R"
	url    = "/"
	weight = 0
	
[[menu.main]]
	name   = "Hello World"
	url    = "hello-world/"
	weight = 10


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
