---
title: "Respostas: R como calculadora"
author: "Athos Damiani, Daniel Falbel"
date: 2016-11-08
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, fig.path = "figures/")
```

1. 

```{r}
(1 + sqrt(5))/2
```

2. 

```{r}
1/0
-1/0
```

3. 

```{r}
# NaN é o resultado de uma operação matemática inválida. Significa Not A Number
0/0
# NULL é o vazio do R. É como se o objeto não existisse
NULL
a = NULL
is.null(integer(length = 0)) # veja que um vetor, mesmo sem elementos não é NULL
# NA é uma constante lógica do R. Siginifica Not Availlable. NA pode ser 
# convertido para quase todos os tipos de vetores do R. É usado principalmente para
# indicar valores faltantes.
NA
# Inf é significa infinito. É o resultado de operações matemáticas cujo limite é infinito.
1/0
1/Inf
```

5.

```{r}
5 + (3 * 10) %/% 3 == 15
```

6. 

```{r, eval = F}
> x <- 4
> if(x = 4) {
Erro: '=' inesperado in "if(x ="
>   'isso aqui apareceu'
[1] "isso aqui apareceu"
> }
Erro: '}' inesperado in "}"
> x
[1] 4
```

7.

```{r}
x <- 4
if(x == 4) {
  'isso aqui apareceu'
}
x
```

8.

```{r}
for (i in 1:4){
  if(i %% 2 == 0){
    print(paste(i, "elefante(s)", paste(rep("incomoda(m)", times = i), collapse = " "), "muito mais"))
  } else {
   print(paste(i, "elefante(s) incomoda(m) muita gente")) 
  }
}
```

9.

```{r}
x <- c(1, 20, 40, 50, 60)
```

10.

```{r}
x <- runif(100)
```

11.

```{r}
mean(x)
```

12.

```{r}
x <- c(runif(99), NA)
mean(x, na.rm = T)
```

13.

```{r}
media <- function(x){
  i <- 1
  tamanho <- length(x)
  soma <- 0
  for(i in 1:tamanho){
    soma <- soma + x[i]
  }
  return(soma/tamanho)
}
```

14.

```{r}
dado <- function(){
  sample(1:6, 1)
}
```

15.

```{r}
soma_dados <- function(n){
  soma <- 0
  for(i in 1:n){
    soma <- soma + sample(1:6, 1)
  }
  return(soma)
}
```

16.

```{r resp16}
resultados <- integer(length = 1000)
for(i in 1:1000){
  resultados[i] <- soma_dados(3)
}
hist(resultados)
```

